export const INDIRECT_REFERRAL_LIMIT = 5;
export const DIRECT_REFERRAL_PAYMENT = 100;
export const INDIRECT_REFERRAL_PAYMENT = 25;
export const PAIRING_BONUS_PAYMENT = 150;
export const PAIRING_PRODUCT_VOUCHER_PAYMENT = 150;
export const AUTOMATIC_EQUIVALENT_REBATES_PAYMENT = 5;

export const PAIRING_BONUS_MAX_COUNT_PER_DAY = 4;

export const B1T1_PRICE = 350;
export const B2T3_PRICE = 700;

export const COFFEE_PACKAGE_PER_PIN = 5;
export const SOAP_PACKAGE_PER_PIN = 4;

export const ADMIN_REPEAT_PURCHASE_INCOME = 5;

export const ADMIN_NEW_MEMBER_INCOME = 45;
export const MEGA_CENTER_NEW_MEMBER_INCOME = 300;
export const STOCKIST_NEW_MEMBER_INCOME = 300;

export const PAIRING_BONUS_TYPE = "PAIRING_BONUS";
export const PRODUCT_VOUCHER_TYPE = "PRODUCT_VOUCHER";

export const B1T1_MEGA_CENTER_INCOME = 95;
export const B2T3_MEGA_CENTER_INCOME = 62.5;

export const B1T1_STOCKIST_INCOME = 85;
export const B2T3_STOCKIST_INCOME = 37.5;

export const B1T1_AE_REBATES = 5;
export const B2T3_AE_REBATES = 12.5;

export const STOCKIST_REPEAT_PURCHASE_COFFEE = 5;
export const STOCKIST_REPEAT_PURCHASE_SOAP = 2.5;

export const B1T1_STOCKIST_ENCODE_NEW_ORDER = 10;
export const B2T3_STOCKIST_ENCODE_NEW_ORDER = 25;
