export const data = [
  {
    name: 'Dunstan Puckham',
    age: 18,
    city: 'Guohe',
    income: 18867,
  },
  {
    name: 'Carlin Shufflebotham',
    age: 57,
    city: 'Chengbei',
    income: 11577,
  },
  {
    name: 'Bartholomeo Demangeon',
    age: 26,
    city: 'Strasbourg',
    income: 25097,
  },
  {
    name: 'Fleurette Letchmore',
    age: 48,
    city: 'Chicago',
    income: 5581,
  },
  {
    name: 'Borg Pardey',
    age: 46,
    city: 'Yinjiang',
    income: 28194,
  },
  {
    name: 'Morgen Bosenworth',
    age: 45,
    city: 'Pelasgía',
    income: 30606,
  },
  {
    name: 'Paige Ellesmere',
    age: 60,
    city: 'Żelistrzewo',
    income: 7646,
  },
  {
    name: 'Anny Rainforth',
    age: 22,
    city: 'São José de Ribamar',
    income: 31365,
  },
  {
    name: 'Beverlee Yves',
    age: 58,
    city: 'Santos Dumont',
    income: 8380,
  },
  {
    name: 'Crawford Scoon',
    age: 31,
    city: 'Jonkowo',
    income: 27633,
  },
  {
    name: 'Lulu Davidesco',
    age: 42,
    city: 'Nangaroro',
    income: 16274,
  },
  {
    name: 'Robena Akister',
    age: 58,
    city: 'Łąck',
    income: 7858,
  },
  {
    name: 'Aldo Harston',
    age: 40,
    city: 'Zheleznovodsk',
    income: 33881,
  },
  {
    name: 'Andra Stanislaw',
    age: 19,
    city: 'Kuantan',
    income: 38552,
  },
  {
    name: 'Terencio Maryman',
    age: 24,
    city: 'Gesikan',
    income: 21135,
  },
  {
    name: 'Victor Natte',
    age: 33,
    city: 'Shigu',
    income: 34023,
  },
  {
    name: 'Jeanine Golson',
    age: 34,
    city: 'Ciudad Darío',
    income: 24562,
  },
  {
    name: 'Darsie Kasbye',
    age: 55,
    city: 'Jega',
    income: 21687,
  },
  {
    name: 'Vi Ughi',
    age: 22,
    city: 'Puerto Eldorado',
    income: 31964,
  },
  {
    name: 'Mehetabel Waller',
    age: 60,
    city: 'Jinotega',
    income: 31916,
  },
  {
    name: 'Catlee Sayward',
    age: 35,
    city: 'Zernograd',
    income: 39720,
  },
  {
    name: 'Arch Meekings',
    age: 57,
    city: 'Vilémov',
    income: 28379,
  },
  {
    name: 'Dredi Kellogg',
    age: 56,
    city: 'São João dos Patos',
    income: 10138,
  },
  {
    name: 'Reamonn Patsall',
    age: 37,
    city: 'Tumpukrenteng',
    income: 16584,
  },
  {
    name: 'Orlando Bachshell',
    age: 32,
    city: 'Flers',
    income: 16076,
  },
  {
    name: 'Mathilde Hambelton',
    age: 56,
    city: 'Karengan',
    income: 14925,
  },
  {
    name: 'Arnold Berdale',
    age: 36,
    city: 'Nova Kakhovka',
    income: 14528,
  },
  {
    name: 'Jacynth Clelland',
    age: 37,
    city: 'Lagodekhi',
    income: 31068,
  },
  {
    name: 'Astrid Dunlop',
    age: 26,
    city: 'Gagarin',
    income: 39409,
  },
  {
    name: 'Claudian Teesdale',
    age: 47,
    city: 'Marseille',
    income: 25743,
  },
  {
    name: 'Margit Refford',
    age: 42,
    city: 'Vnanje Gorice',
    income: 29670,
  },
  {
    name: 'Violante Chawner',
    age: 26,
    city: 'Daja',
    income: 29090,
  },
  {
    name: 'Clemmy Fackrell',
    age: 46,
    city: 'Golem',
    income: 25398,
  },
  {
    name: 'Keary Flower',
    age: 25,
    city: 'Hénin-Beaumont',
    income: 21400,
  },
  {
    name: 'Cleo Barfield',
    age: 55,
    city: 'Gaojialing',
    income: 18464,
  },
  {
    name: "Bernita D'orsay",
    age: 19,
    city: 'Labuhan',
    income: 32435,
  },
  {
    name: 'Charity Beric',
    age: 53,
    city: 'Tsalka',
    income: 21414,
  },
  {
    name: 'Elijah Huison',
    age: 55,
    city: 'Tundagan',
    income: 28125,
  },
  {
    name: 'Amil Wawer',
    age: 51,
    city: 'Koceljeva',
    income: 30388,
  },
  {
    name: 'Faye Tolomei',
    age: 50,
    city: 'Berbek',
    income: 17753,
  },
  {
    name: 'Sharon Cleal',
    age: 20,
    city: 'Jatisari',
    income: 36802,
  },
  {
    name: 'Doralin Pigford',
    age: 48,
    city: 'Linares',
    income: 32092,
  },
  {
    name: 'Chickie Chastang',
    age: 60,
    city: 'Semypolky',
    income: 13418,
  },
  {
    name: 'Amargo Blenkinsopp',
    age: 36,
    city: 'Selce',
    income: 6891,
  },
  {
    name: 'Maribelle Le Merchant',
    age: 49,
    city: 'Shuangmiaojie',
    income: 20186,
  },
  {
    name: 'Alexa Ramiro',
    age: 47,
    city: 'El Paso',
    income: 7570,
  },
  {
    name: 'Liz Alexandrou',
    age: 35,
    city: 'Stará Ves nad Ondřejnicí',
    income: 30391,
  },
  {
    name: 'Lenna Voss',
    age: 32,
    city: 'Riachão do Jacuípe',
    income: 18376,
  },
  {
    name: 'Arlee Riccelli',
    age: 49,
    city: 'San Andrés Xecul',
    income: 35086,
  },
  {
    name: 'Magda Manson',
    age: 52,
    city: 'Zaranj',
    income: 17811,
  },
  {
    name: 'Felisha MacKniely',
    age: 26,
    city: 'Caminaca',
    income: 33736,
  },
  {
    name: 'Martelle Czyz',
    age: 18,
    city: 'Tanjung Kidul',
    income: 25552,
  },
  {
    name: 'Torie Janks',
    age: 28,
    city: 'Jawl al Majma‘',
    income: 27756,
  },
  {
    name: 'Ivor Abbotts',
    age: 47,
    city: 'Radviliskis',
    income: 22694,
  },
  {
    name: 'Hollyanne Pethick',
    age: 46,
    city: 'Irosin',
    income: 34586,
  },
  {
    name: 'Nicolina Blundon',
    age: 27,
    city: 'Urkarakh',
    income: 11471,
  },
  {
    name: 'Luisa Warters',
    age: 21,
    city: 'Wesoła',
    income: 11570,
  },
  {
    name: 'Marcos Pegden',
    age: 43,
    city: 'Orléans',
    income: 31416,
  },
  {
    name: 'Elisabeth Elton',
    age: 31,
    city: 'Lubomierz',
    income: 26524,
  },
  {
    name: 'Vidovik Zellmer',
    age: 49,
    city: 'Kranuan',
    income: 37848,
  },
  {
    name: 'Caressa Okey',
    age: 35,
    city: 'Gaozhai',
    income: 4152,
  },
  {
    name: 'Nelie Breckon',
    age: 51,
    city: 'Otyń',
    income: 18910,
  },
  {
    name: 'Roxine Morforth',
    age: 49,
    city: 'Uritsk',
    income: 14450,
  },
  {
    name: 'Corabella Conradsen',
    age: 19,
    city: 'Tabonok',
    income: 4638,
  },
  {
    name: 'Vickie Tudge',
    age: 26,
    city: 'Dananshan',
    income: 2854,
  },
  {
    name: 'Abraham Brittan',
    age: 32,
    city: 'Goim',
    income: 16346,
  },
  {
    name: 'Brockie Tripp',
    age: 56,
    city: 'Qiongshan',
    income: 23396,
  },
  {
    name: 'Harlen Father',
    age: 48,
    city: 'Hengpi',
    income: 25107,
  },
  {
    name: 'Emalee Wrangle',
    age: 25,
    city: 'Torsås',
    income: 9824,
  },
  {
    name: 'Pattie Cutsforth',
    age: 31,
    city: 'Mérignac',
    income: 19290,
  },
  {
    name: 'Carlynn Hendron',
    age: 50,
    city: 'Kedungcangkring',
    income: 9054,
  },
  {
    name: 'Nikos Lomaz',
    age: 43,
    city: 'Kedungwaru',
    income: 39802,
  },
  {
    name: 'Garret Albert',
    age: 52,
    city: 'Yola',
    income: 12838,
  },
  {
    name: 'Katlin Castangia',
    age: 43,
    city: 'Bela Vista',
    income: 13551,
  },
  {
    name: 'Jobi Egglestone',
    age: 18,
    city: 'Trinidad',
    income: 7197,
  },
  {
    name: 'Zorina Fidgett',
    age: 39,
    city: 'Boituva',
    income: 24818,
  },
  {
    name: 'Gillian Boyd',
    age: 59,
    city: 'Poja',
    income: 17960,
  },
  {
    name: 'Karlens Coutts',
    age: 21,
    city: 'Fontem',
    income: 16968,
  },
  {
    name: 'Meredithe Gonzales',
    age: 33,
    city: 'Budenovetc',
    income: 2964,
  },
  {
    name: 'Susanna Janaud',
    age: 56,
    city: 'Nunguan',
    income: 7613,
  },
  {
    name: 'Puff Mosconi',
    age: 28,
    city: 'Fengkou',
    income: 13643,
  },
  {
    name: 'Ediva Bennen',
    age: 53,
    city: 'Patrocínio',
    income: 17770,
  },
  {
    name: 'Orelia Sherrington',
    age: 45,
    city: 'Sukamahi Satu',
    income: 27068,
  },
  {
    name: 'Stanfield Karp',
    age: 59,
    city: 'Ferreiros',
    income: 14231,
  },
  {
    name: 'Ariela Prester',
    age: 47,
    city: 'Viçosa do Ceará',
    income: 26559,
  },
  {
    name: 'Noellyn Cornhill',
    age: 48,
    city: 'Novopodrezkovo',
    income: 18454,
  },
  {
    name: 'Mitchael Cervantes',
    age: 25,
    city: 'Yanbei',
    income: 36022,
  },
  {
    name: 'Thor Pawlowicz',
    age: 57,
    city: 'Okahandja',
    income: 24504,
  },
  {
    name: 'Bondie Vynehall',
    age: 55,
    city: 'Candelaria',
    income: 13643,
  },
  {
    name: 'Rollins Kropach',
    age: 43,
    city: 'Lanat',
    income: 31022,
  },
  {
    name: 'Milli Sellers',
    age: 19,
    city: 'Cagnes-sur-Mer',
    income: 24234,
  },
  {
    name: 'Scot Daenen',
    age: 34,
    city: 'Hampang',
    income: 18983,
  },
  {
    name: 'Micki Yakhin',
    age: 52,
    city: 'Palopat',
    income: 27993,
  },
  {
    name: 'Kameko Cline',
    age: 48,
    city: 'Beja',
    income: 28990,
  },
  {
    name: 'Wilburt Giacomuzzo',
    age: 60,
    city: 'Enskede',
    income: 22350,
  },
  {
    name: 'Bobine Garr',
    age: 35,
    city: 'Taremskoye',
    income: 10603,
  },
  {
    name: 'Velma Pawlyn',
    age: 23,
    city: 'Sarnaki',
    income: 14018,
  },
  {
    name: 'Aurea Jorio',
    age: 38,
    city: 'Sergelen',
    income: 26939,
  },
  {
    name: 'Silvester Cadney',
    age: 20,
    city: 'Guanqiao',
    income: 20864,
  },
  {
    name: 'Ricky Santer',
    age: 59,
    city: 'Bojen Kulon',
    income: 2469,
  },
];
